#ifndef LUMEX_MACROS_HPP
#define LUMEX_MACROS_HPP

#define LUMEX_STRINGIZE_DETAIL(x) #x
#define LUMEX_STRINGIZE(x) LUMEX_STRINGIZE_DETAIL(x)

#define LUMEX_CONCAT_DETAIL(x, y) x##y
#define LUMEX_CONCAT(x, y) LUMEX_CONCAT_DETAIL(x, y)

#endif // !LUMEX_MACROS_HPP
