/**
 * Copyright (c) 2026 Vladislav Semykin <vladislav.semykin@gmail.com>
 *
 *
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of
 * charge, to any person obtaining a copy
 * of this software and associated
 * documentation files (the "Software"), to deal
 * in the Software without
 * restriction, including without limitation the rights
 * to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the
 * Software, and to permit persons to whom the Software is
 * furnished to do
 * so, subject to the following conditions:
 *
 * The above copyright notice
 * and this permission notice shall be included in
 * all copies or substantial
 * portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
 * WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH
 * THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef LUMEX_APPLIED_SETTINGS_INI_SUPPORTED_CONFIG_EXTENSIONS_HPP
#define LUMEX_APPLIED_SETTINGS_INI_SUPPORTED_CONFIG_EXTENSIONS_HPP

#include <cstdint>

namespace lumex // NOLINT(modernize-concat-nested-namespaces)
{
namespace applied
{
namespace settings
{
namespace ini
{
/**
 * @brief Enumeration of supported configuration file formats.
 * @details Defines the file formats that can be parsed or generated by the
 * settings system. INI is always available. XML is created by the factory
 * when `LUMEX_SETTINGS_WITH_XML` is defined (effective `LUMEX_BUILD_XML`).
 * JSON is created when `LUMEX_SETTINGS_WITH_JSON` is defined (vendored
 * nlohmann/json header present). YAML remains a placeholder.
 * @note Extend this enum when adding support for new file formats.
 */
enum SupportedConfigExtensions : std::uint8_t
{
  INI,  ///< INI file format (key-value pairs with sections).
  XML,  ///< XML file format via `LumexSettingsXML` / `LumexXml`.
  JSON, ///< JSON file format via `LumexSettingsJSON` / nlohmann.
        // YAML, // add YAML
};
} // namespace ini
} // namespace settings
} // namespace applied
} // namespace lumex

using LumexSettingsExtensions
    = lumex::applied::settings::ini::SupportedConfigExtensions;

#endif // !LUMEX_APPLIED_SETTINGS_INI_SUPPORTED_CONFIG_EXTENSIONS_HPP
