include("${LUMEX_SOURCE_DIR}/lumex/tests/cmake/setup_all_on.cmake")
include("${LUMEX_SOURCE_DIR}/cmake/LumexModules.cmake")

function(_assert_effective opt_var expected)
    lumex_effective_on(_got "${opt_var}")
    if(expected AND NOT _got)
        message(FATAL_ERROR "expected ${opt_var} effective ON")
    endif()
    if(NOT expected AND _got)
        message(FATAL_ERROR "expected ${opt_var} effective OFF")
    endif()
endfunction()

_assert_effective(LUMEX_BUILD_BASE64 TRUE)
_assert_effective(LUMEX_BUILD_HARDWARE TRUE)
_assert_effective(LUMEX_BUILD_XML TRUE)
_assert_effective(LUMEX_BUILD_CORE TRUE)

set(LUMEX_BUILD_CORE OFF)
_assert_effective(LUMEX_BUILD_BASE64 FALSE)
_assert_effective(LUMEX_BUILD_UTILITY FALSE)
_assert_effective(LUMEX_BUILD_CORE FALSE)
_assert_effective(LUMEX_BUILD_HARDWARE TRUE)
_assert_effective(LUMEX_BUILD_XML TRUE)
set(LUMEX_BUILD_CORE ON)

set(LUMEX_BUILD_TIME OFF)
_assert_effective(LUMEX_BUILD_TIME FALSE)
_assert_effective(LUMEX_BUILD_UTILITY TRUE)
set(LUMEX_BUILD_TIME ON)

set(LUMEX_BUILD_APPLIED OFF)
_assert_effective(LUMEX_BUILD_HARDWARE FALSE)
_assert_effective(LUMEX_BUILD_LOGGER FALSE)
_assert_effective(LUMEX_BUILD_BASE64 TRUE)
set(LUMEX_BUILD_APPLIED ON)

set(LUMEX_BUILD_XML OFF)
_assert_effective(LUMEX_BUILD_XML FALSE)
set(LUMEX_BUILD_XML ON)
