set(LUMEX_USE_ASAN OFF)
set(LUMEX_USE_UBSAN ON)
set(LUMEX_USE_TSAN OFF)
set(CMAKE_BUILD_TYPE Release)
unset(CMAKE_CONFIGURATION_TYPES)
include("${CMAKE_CURRENT_LIST_DIR}/_sanitizer_build_type.cmake")
lumex_run_sanitizer_build_type_check(TRUE)
