#ifndef SUPPORTED_CONFIG_EXTENSIONS_HPP
#define SUPPORTED_CONFIG_EXTENSIONS_HPP

#include <cstdint>

namespace Lumex // NOLINT(modernize-concat-nested-namespaces)
{
  namespace Applied
  {
    namespace Settings
    {
      /**
       * @brief Enumeration of supported configuration file formats.
       * @details Defines the file formats that can be parsed or generated by the settings system.
       *          Currently supports INI, with placeholders for future formats (JSON, YAML, XML).
       * @note Extend this enum when adding support for new file formats.
       */
      enum SupportedConfigExtensions : std::uint8_t
      {
        INI, ///< INI file format (key-value pairs with sections).
             // JSON, // add JSON
             // YAML, // add YAML
             // XML,  // add XML
      };
    } // namespace Settings
  } // namespace Applied
} // namespace Lumex

using LumexSettingsExtensions = Lumex::Applied::Settings::SupportedConfigExtensions;

#endif // !SUPPORTED_CONFIG_EXTENSIONS_HPP
